### PR TITLE
fix(readme): Update recommended setting

### PR DESCRIPTION
**Pull request by qadzek**
It appears that the syntax for this setting has changed. The current example returns the following error: `Incorrect type. Expected "string".`

It also might be useful to limit this setting to JSON files.

### CODE REVIEW

**Comment by zardoy** [comment]
> It also might be useful to limit this setting to JSON files.

Makes sense, but then, add jsonc language as well so we have `[json][jsonc]`

**Comment by qadzek** [comment]
Good idea.

Thanks for this extension. Having to add or remove trailing commas in JSON files was always quite a hassle.

**Comment by zardoy** [comment]
Sorry, not at home right now but I want to check that setting syntax change, that why it will take some time to merge

**Comment by zardoy** [comment]
> Incorrect type. Expected "string"

Okay, I see. But why do you change the setting value from `true` to `["source.fixAll"]` (which is string[])?

**Comment by zardoy** [comment]
Ok, I see that the provided format also works, I just expected it to be changed to

```json
"editor.codeActionsOnSave": {
    "source.fixAll": "explicit"
  }
```

**Comment by zardoy** [comment]
> Thanks for this extension. Having to add or remove trailing commas in JSON files was always quite a hassle.

Thanks, I'm glad someone in the world discovered this one!

**Pull request merged**
